on:
  push:
      branches: [main]
  pull_request:
      branches: [main]

jobs:
  build-and-test:
    name: build and test application
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: setup environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.6"

      - name: install dependencies
        run: pip install -r requirements.txt
      
      - name: pytest
        run: pytest